<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parents = [
            [
                'student_id' => 1,
                'father_name' => 'AAS BENI HIDAYAT',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'AAH SOLIHAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:10',
            ],
            [
                'student_id' => 2,
                'father_name' => 'WARDIMAN',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'LILIS LISNAWATI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:41',
            ],
            [
                'student_id' => 3,
                'father_name' => 'DIDI JUMADI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Devi Sintiawati',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:47',
            ],
            [
                'student_id' => 4,
                'father_name' => 'HERI PERMANA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Fidiyawati',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:53',
            ],
            [
                'student_id' => 5,
                'father_name' => 'AJIS',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Fuji Fauziah',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:47',
            ],
            [
                'student_id' => 6,
                'father_name' => 'SAEPULOH',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Lilis Lisnawati',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:06',
            ],
            [
                'student_id' => 7,
                'father_name' => 'SUPRIATNA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Sri Wahyuningsih',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:17',
            ],
            [
                'student_id' => 8,
                'father_name' => 'AGIS ROHIMAT',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Resti Firdayanti',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:32',
            ],
            [
                'student_id' => 9,
                'father_name' => 'AHMAD SUJAI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'IIS RODIAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:40',
            ],
            [
                'student_id' => 10,
                'father_name' => 'AAS AGIS KUSWAYA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'CICI PARLINA',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:55',
            ],
            [
                'student_id' => 11,
                'father_name' => 'AGUS HERYANA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'NUR NURJANAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:56',
            ],
            [
                'student_id' => 12,
                'father_name' => 'JEJEN JENAL ARIPIN',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ELIN HERLINA',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:48',
            ],
            [
                'student_id' => 13,
                'father_name' => 'SYARIF HIDAYAT',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ELY YULIA',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:43:02',
            ],
            [
                'student_id' => 14,
                'father_name' => 'NANANG FRIATNA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ENOK HERLINA',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:37:50',
            ],
            [
                'student_id' => 15,
                'father_name' => 'DALI PERMADI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'YATI SURYATI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:19',
            ],
            [
                'student_id' => 16,
                'father_name' => 'DEDE MULYADI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ANTI ROSTIANTI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:27',
            ],
            [
                'student_id' => 17,
                'father_name' => 'SANUSI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'RAHMAWATI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:51',
            ],
            [
                'student_id' => 18,
                'father_name' => 'HENDI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'SITI AISAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:05',
            ],
            [
                'student_id' => 19,
                'father_name' => 'CECEP SAHARA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'SITI MARDIANAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:15',
            ],
            [
                'student_id' => 20,
                'father_name' => 'DODO HENDRA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ATIN SUPRIATIN',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:26',
            ],
            [
                'student_id' => 21,
                'father_name' => 'EDI SUPRIADI',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ENTIK TATI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:34',
            ],
            [
                'student_id' => 22,
                'father_name' => 'JAJANG SURYANA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'IMAS RAHMAWATI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:43',
            ],
            [
                'student_id' => 23,
                'father_name' => 'ASEP DODO',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'WARI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:02',
            ],
            [
                'student_id' => 24,
                'father_name' => 'AZIS MUSLIM',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'RINI YANTI RAHAYU',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:10',
            ],
            [
                'student_id' => 25,
                'father_name' => 'ASEP SAEPULLOH',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'SITI KHOERIAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:18',
            ],
            [
                'student_id' => 26,
                'father_name' => 'AEP SAEPULLOH',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'SITI KHOERIAH',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:26',
            ],
            [
                'student_id' => 27,
                'father_name' => 'NANANG FARIDUDIN',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'Enung Nurhayati',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:34',
            ],
            [
                'student_id' => 28,
                'father_name' => 'MUHAMAD TOHA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'IIF SARIPAH S.PD',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:55',
            ],
            [
                'student_id' => 29,
                'father_name' => 'DENI HERDIANA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'ATIK IRAWATI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:43:09',
            ],
            [
                'student_id' => 30,
                'father_name' => 'AGUS SANJAYA',
                'father_job' => null,
                'father_phone' => '',
                'mother_name' => 'MAYASARI MAHARANI',
                'mother_job' => null,
                'mother_phone' => '',
                'guardian_name' => null,
                'guardian_job' => null,
                'guardian_phone' => null,
                'photo_url' => null,
                'password_hash' => 'Alislam123',
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:43:17',
            ],
        ];

        foreach ($parents as $parent) {
            \DB::table('parents')->updateOrInsert(
                ['student_id' => $parent['student_id']],
                $parent
            );
        }
    }
}
