<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'nisn' => '3200194909',
                'nis' => '250001',
                'name' => 'AKHSAN RAMADHAN',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-05-12',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:10',
            ],
            [
                'nisn' => '3208188033',
                'nis' => '250002',
                'name' => 'ALINNA TRI WULANDARY',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-08-30',
                'religion' => '1',
                'address' => 'DUSUN SUBANG, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:41',
            ],
            [
                'nisn' => '3201873261',
                'nis' => '250003',
                'name' => 'DANU GHILMAN HADIYAN',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-04-18',
                'religion' => '1',
                'address' => 'SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:47',
            ],
            [
                'nisn' => '3207734540',
                'nis' => '250005',
                'name' => 'MUHAMMAD KENZIE PUTRA PERMANA',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'BOYOLALI',
                'birth_date' => '2020-06-17',
                'religion' => '1',
                'address' => 'SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:53',
            ],
            [
                'nisn' => '3202043565',
                'nis' => '250006',
                'name' => 'NISA NURAFIFAH AZ-ZAHRA',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-05-10',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:44',
            ],
            [
                'nisn' => '3204694103',
                'nis' => '250008',
                'name' => 'RAFA AL TAUFIQ',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-02-24',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:06',
            ],
            [
                'nisn' => '3201208113',
                'nis' => '250009',
                'name' => 'RAZKA WILIAM SAPUTRA',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-08-08',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:17',
            ],
            [
                'nisn' => '3203334373',
                'nis' => '250010',
                'name' => 'RIENTAMMY NAZIA PUTRIE',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-09-26',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:32',
            ],
            [
                'nisn' => '3204587629',
                'nis' => '250011',
                'name' => 'RIRIN SOPIYAH',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-12-11',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:40',
            ],
            [
                'nisn' => '3202885958',
                'nis' => '250004',
                'name' => 'FAHMI KAMAL ALGHANI',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-11-09',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:55',
            ],
            [
                'nisn' => '3194033181',
                'nis' => '250007',
                'name' => 'NOVIAN MAHARDIKA',
                'class_id' => 1,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-11-24',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:56',
            ],
            [
                'nisn' => '3209312801',
                'nis' => '250012',
                'name' => 'SHAQILA NURHASANAH',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-04-18',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:48',
            ],
            [
                'nisn' => '3206684539',
                'nis' => '250013',
                'name' => 'SYAKILA ALMAIRA',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-09-18',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:43:02',
            ],
            [
                'nisn' => '3185384514',
                'nis' => '240001',
                'name' => 'ABIDZARD HILMI FAUZIANSYAH',
                'class_id' => 2,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2018-09-27',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:37:50',
            ],
            [
                'nisn' => '3191564790',
                'nis' => '240002',
                'name' => 'AL AYYUBY FAIZ',
                'class_id' => 2,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-09-04',
                'religion' => '1',
                'address' => 'DUSUN SUBANG, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:19',
            ],
            [
                'nisn' => '3186404777',
                'nis' => '240003',
                'name' => 'ALESHA MAULIDA',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2018-11-11',
                'religion' => '1',
                'address' => 'DUSUN RANJI RATA, Kel. CIMARI, Kec. CIKONENG, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:27',
            ],
            [
                'nisn' => '3196018725',
                'nis' => '240004',
                'name' => 'AMELIA RAHMA JULIANTI',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-07-01',
                'religion' => '1',
                'address' => 'DUSUN SUBANG, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:38:51',
            ],
            [
                'nisn' => '3186781982',
                'nis' => '250014',
                'name' => 'ANNISA NURRUL QOLBY',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2018-12-27',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:05',
            ],
            [
                'nisn' => '3205309254',
                'nis' => '240005',
                'name' => 'AZKIA ZAHRA NURSIFA',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-04-05',
                'religion' => '1',
                'address' => 'SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:39:15',
            ],
            [
                'nisn' => '3198820898',
                'nis' => '240006',
                'name' => 'HAFIZ NAJWAN',
                'class_id' => 2,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-10-25',
                'religion' => '1',
                'address' => 'DUSUN SUBANG, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:26',
            ],
            [
                'nisn' => '3199037426',
                'nis' => '240007',
                'name' => 'HANIF HUSNI RAMADHAN',
                'class_id' => 2,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-05-28',
                'religion' => '1',
                'address' => 'DUSUN SUBANG, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:34',
            ],
            [
                'nisn' => '3196993818',
                'nis' => '240008',
                'name' => 'HILYA DWI ANNAURI',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-05-02',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:40:43',
            ],
            [
                'nisn' => '3196285378',
                'nis' => '240009',
                'name' => 'MUHAMMAD LUTHFI IBNU HAFIDZ',
                'class_id' => 2,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-07-11',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:02',
            ],
            [
                'nisn' => '3195329264',
                'nis' => '240010',
                'name' => 'MUHAMMAD RAFI HAFIZ ALFATIH',
                'class_id' => 2,
                'gender' => 'L',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-05-04',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:10',
            ],
            [
                'nisn' => '3196449784',
                'nis' => '240011',
                'name' => 'NABILA NUR AZIZAH',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-02-27',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:18',
            ],
            [
                'nisn' => '3192889481',
                'nis' => '240012',
                'name' => 'NADIFA NURUL JANNAH',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-02-27',
                'religion' => '1',
                'address' => 'SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:26',
            ],
            [
                'nisn' => '3195070489',
                'nis' => '250015',
                'name' => 'NADZIFAH JAUHAR NAFISAH',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-02-06',
                'religion' => '1',
                'address' => 'SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:41:34',
            ],
            [
                'nisn' => '3206313252',
                'nis' => '250016',
                'name' => 'SHOFA NURSYIFA HASANAH',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2020-02-02',
                'religion' => '1',
                'address' => 'DUSUN SIRNAGALIH, Kel. GUNUNGCUPU, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:42:55',
            ],
            [
                'nisn' => '3194469072',
                'nis' => '250017',
                'name' => 'SYASHA SHIDQIA',
                'class_id' => 1,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-09-12',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:43:09',
            ],
            [
                'nisn' => '3190130709',
                'nis' => '240013',
                'name' => 'YOLLA OLIVIA',
                'class_id' => 2,
                'gender' => 'P',
                'birth_place' => 'CIAMIS',
                'birth_date' => '2019-02-07',
                'religion' => '1',
                'address' => 'DUSUN TUGU, Kel. SUKASENANG, Kec. SINDANGKASIH, JAWA BARAT, 46268',
                'photo_url' => null,
                'qr_code_path' => null,
                'created_at' => '2026-01-09 12:24:19',
                'updated_at' => '2026-01-09 12:43:17',
            ],
        ];

        foreach ($students as $student) {
            \DB::table('students')->updateOrInsert(
                ['nisn' => $student['nisn']],
                $student
            );
        }
    }
}
