<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Administrator',
                'email' => 'admin@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\Guru',
                'userable_id' => 1,
                'email_verified_at' => null,
                'password' => Hash::make('admin123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'J67gyKgELPhWY1xa2Kpf0p9y0DjfLqZ4DTkMbU5gLbzLz6vUfwlwVykNi5AK',
                'created_at' => '2026-01-17 01:44:57',
                'updated_at' => '2026-01-19 11:01:26',
            ],
            [
                'name' => 'Eulis Sukmayati',
                'email' => 'eulis-sukmayati@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\Guru',
                'userable_id' => 2,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:27',
                'updated_at' => '2026-01-19 11:01:27',
            ],
            [
                'name' => 'Elis Nurjanah',
                'email' => 'elis-nurjanah@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\Guru',
                'userable_id' => 3,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:28',
                'updated_at' => '2026-01-19 11:01:28',
            ],
            [
                'name' => 'Ecin Nurbayanti',
                'email' => 'ecin-nurbayanti@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\Guru',
                'userable_id' => 4,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:29',
                'updated_at' => '2026-01-19 11:01:29',
            ],
            [
                'name' => 'Lilis Farida',
                'email' => 'lilis-farida@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\Guru',
                'userable_id' => 5,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:30',
                'updated_at' => '2026-01-19 11:01:30',
            ],
            [
                'name' => 'AAS BENI HIDAYAT',
                'email' => '250001@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 1,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:31',
                'updated_at' => '2026-01-19 11:01:31',
            ],
            [
                'name' => 'WARDIMAN',
                'email' => '250002@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 2,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:32',
                'updated_at' => '2026-01-19 11:01:32',
            ],
            [
                'name' => 'DIDI JUMADI',
                'email' => '250003@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 3,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:33',
                'updated_at' => '2026-01-19 11:01:33',
            ],
            [
                'name' => 'HERI PERMANA',
                'email' => '250005@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 4,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:33',
                'updated_at' => '2026-01-19 11:01:33',
            ],
            [
                'name' => 'AJIS',
                'email' => '250006@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 5,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:34',
                'updated_at' => '2026-01-19 11:01:34',
            ],
            [
                'name' => 'SAEPULOH',
                'email' => '250008@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 6,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:35',
                'updated_at' => '2026-01-19 11:01:35',
            ],
            [
                'name' => 'SUPRIATNA',
                'email' => '250009@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 7,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:36',
                'updated_at' => '2026-01-19 11:01:36',
            ],
            [
                'name' => 'AGIS ROHIMAT',
                'email' => '250010@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 8,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:38',
                'updated_at' => '2026-01-19 11:01:38',
            ],
            [
                'name' => 'AHMAD SUJAI',
                'email' => '250011@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 9,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:39',
                'updated_at' => '2026-01-19 11:01:39',
            ],
            [
                'name' => 'AAS AGIS KUSWAYA',
                'email' => '250004@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 10,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:40',
                'updated_at' => '2026-01-19 11:01:40',
            ],
            [
                'name' => 'AGUS HERYANA',
                'email' => '250007@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 11,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:41',
                'updated_at' => '2026-01-19 11:01:41',
            ],
            [
                'name' => 'JEJEN JENAL ARIPIN',
                'email' => '250012@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 12,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:42',
                'updated_at' => '2026-01-19 11:01:42',
            ],
            [
                'name' => 'SYARIF HIDAYAT',
                'email' => '250013@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 13,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:43',
                'updated_at' => '2026-01-19 11:01:43',
            ],
            [
                'name' => 'NANANG FRIATNA',
                'email' => '240001@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 14,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:44',
                'updated_at' => '2026-01-19 11:01:44',
            ],
            [
                'name' => 'DALI PERMADI',
                'email' => '240002@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 15,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:45',
                'updated_at' => '2026-01-19 11:01:45',
            ],
            [
                'name' => 'DEDE MULYADI',
                'email' => '240003@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 16,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:45',
                'updated_at' => '2026-01-19 11:01:45',
            ],
            [
                'name' => 'SANUSI',
                'email' => '240004@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 17,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:46',
                'updated_at' => '2026-01-19 11:01:46',
            ],
            [
                'name' => 'HENDI',
                'email' => '250014@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 18,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:47',
                'updated_at' => '2026-01-19 11:01:47',
            ],
            [
                'name' => 'CECEP SAHARA',
                'email' => '240005@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 19,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:48',
                'updated_at' => '2026-01-19 11:01:48',
            ],
            [
                'name' => 'DODO HENDRA',
                'email' => '240006@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 20,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:49',
                'updated_at' => '2026-01-19 11:01:49',
            ],
            [
                'name' => 'EDI SUPRIADI',
                'email' => '240007@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 21,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:50',
                'updated_at' => '2026-01-19 11:01:50',
            ],
            [
                'name' => 'JAJANG SURYANA',
                'email' => '240008@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 22,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:51',
                'updated_at' => '2026-01-19 11:01:51',
            ],
            [
                'name' => 'ASEP DODO',
                'email' => '240009@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 23,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:52',
                'updated_at' => '2026-01-19 11:01:52',
            ],
            [
                'name' => 'AZIS MUSLIM',
                'email' => '240010@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 24,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:53',
                'updated_at' => '2026-01-19 11:01:53',
            ],
            [
                'name' => 'ASEP SAEPULLOH',
                'email' => '240011@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 25,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:54',
                'updated_at' => '2026-01-19 11:01:54',
            ],
            [
                'name' => 'AEP SAEPULLOH',
                'email' => '240012@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 26,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:56',
                'updated_at' => '2026-01-19 11:01:56',
            ],
            [
                'name' => 'NANANG FARIDUDIN',
                'email' => '250015@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 27,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:57',
                'updated_at' => '2026-01-19 11:01:57',
            ],
            [
                'name' => 'MUHAMAD TOHA',
                'email' => '250016@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 28,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:57',
                'updated_at' => '2026-01-19 11:01:57',
            ],
            [
                'name' => 'DENI HERDIANA',
                'email' => '250017@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 29,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:58',
                'updated_at' => '2026-01-19 11:01:58',
            ],
            [
                'name' => 'AGUS SANJAYA',
                'email' => '240013@ra-alislam.sch.id',
                'userable_type' => 'App\\Models\\ParentModel',
                'userable_id' => 30,
                'email_verified_at' => null,
                'password' => Hash::make('Alislam123'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-01-19 11:01:59',
                'updated_at' => '2026-01-19 11:01:59',
            ],
        ];

        foreach ($users as $user) {
            \DB::table('users')->updateOrInsert(
                ['email' => $user['email']],
                $user
            );
        }
    }
}
